apiVersion: v1
kind: Secret
metadata:
  name: kubeslice-admission-webhook-certs
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNwRENDQWttZ0F3SUJBZ0lRQ1drS0lNYWJObUY4SW1sa3dlL1psekFLQmdncWhrak9QUVFEQWpBYk1Sa3cKRndZRFZRUURFeEJ0ZVMxelpXeG1jMmxuYm1Wa0xXTmhNQjRYRFRJeU1ESXhOakV4TkRJeU0xb1hEVEl5TURVeApOekV4TkRJeU0xb3dBRENDQVNJd0RRWUpLb1pJaHZjTkFRRUJCUUFEZ2dFUEFEQ0NBUW9DZ2dFQkFLc1RsZGkyCjVwb3U3SGwzREF2ekJycUlKWHozKytwMG9TeWdaUlRYcThxRUZUMllEamdWcmk4ekJqN2FzZWtoTSttcTV0Y2UKS0VVM3dEZFcvSCtjQnFWcnJWeDVBTFNpMjhkakhTY0grVkFoVFgrajgzcGlaM21mN2RibWFoM1lRSDVIcFFiVQpNclU2MHM4TlliWndZUGQ0QWM0VldLTnNFUXlDOHlzRHZpNFpteVVHVTBJZWNWQzQrNkczQkhxQTM4T0plTUZ3CnZRYlBXSHZOZFoyMkhhWnVEUU1rY3V2dEJJV0Y4by9qR1h0U01JVlMzZnBFVlBiQ1RMMXdtWnNjS3ZKYktKTTAKSnptNGxxUVVZd09WeGVab1FSTU0vdjNtdW9IRHViQWxHNVlYcmdGSjl6SXlla01QQmcxNVhqMVp5U0MwV0paYgpXQURBNHB1b2FEOHRBcThDQXdFQUFhT0J2akNCdXpBT0JnTlZIUThCQWY4RUJBTUNCYUF3REFZRFZSMFRBUUgvCkJBSXdBREFmQmdOVkhTTUVHREFXZ0JTR09aOVo1ZHREMWVEYSsvbnMxRHZ1SGc4VmNUQjZCZ05WSFJFQkFmOEUKY0RCdWdpNXJkV0psYzJ4cFkyVXRkMlZpYUc5dmF5MXpaWEoyYVdObExtdDFZbVZ6YkdsalpTMXplWE4wWlcwdQpjM1pqZ2p4cmRXSmxjMnhwWTJVdGQyVmlhRzl2YXkxelpYSjJhV05sTG10MVltVnpiR2xqWlMxemVYTjBaVzB1CmMzWmpMbU5zZFhOMFpYSXViRzlqWVd3d0NnWUlLb1pJemowRUF3SURTUUF3UmdJaEFOUEhKQTJhaTVvWnhwemgKOHNkMXVyNDMxb2hScno3UXZuK3BVbFRiU2UzTUFpRUF6RDF0TnpyNFFCbkZVUlNKZW9qYVh0VWtYZzROazRNSQpobzFJUkNDRS9ZVT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
  tls.key: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFcEFJQkFBS0NBUUVBcXhPVjJMYm1taTdzZVhjTUMvTUd1b2dsZlBmNzZuU2hMS0JsRk5lcnlvUVZQWmdPCk9CV3VMek1HUHRxeDZTRXo2YXJtMXg0b1JUZkFOMWI4ZjV3R3BXdXRYSGtBdEtMYngyTWRKd2Y1VUNGTmY2UHoKZW1KbmVaL3QxdVpxSGRoQWZrZWxCdFF5dFRyU3p3MWh0bkJnOTNnQnpoVllvMndSRElMekt3TytMaG1iSlFaVApRaDV4VUxqN29iY0Vlb0RmdzRsNHdYQzlCczlZZTgxMW5iWWRwbTROQXlSeTYrMEVoWVh5aitNWmUxSXdoVkxkCitrUlU5c0pNdlhDWm14d3E4bHNva3pRbk9iaVdwQlJqQTVYRjVtaEJFd3orL2VhNmdjTzVzQ1VibGhldUFVbjMKTWpKNlF3OEdEWGxlUFZuSklMUllsbHRZQU1EaW02aG9QeTBDcndJREFRQUJBb0lCQUhIYUMreDQ5SWtCMTNDUwpzSnEzTnZBbXNVUTB5UnRrV09zWko0d3laK3JUOGtyV2lnZjdMYnZOcWtka1JlaVBwenZIOSs2TDdHTDhVbGpCCjlESjh4Tk9NRUlpdElySVVmRTE2Z2FrN0hrbWNrRFgxQjVHWU1hTDRzMUZFY0xUQitWSFJIbHVvRnNNVGpiNHIKK3E1dXBhbXIzUStvbHgvVFNKbGFBTGpNdWVGMUk5NTIzekQyU1lMVG82OVYwZGRYUnNnMjhXUHFhOHZ5UlJMSApxcmtwSUxLeHQ3M2tMM28zN1lxUXZOeW82T1RUWlhUbHVPUVVFTmU3ekZWWHFuVlJaRVhtUmV0OGk5SzFhZCtFCmV1RlZucWJySVZHNjRwRkFhb2k0QWQ5cWpOU2YzZm10aE9Gd0s4ZVVkU0RPcGdnakdFTC9jOENtSUdFd3BqUUEKUTIwN0JYRUNnWUVBdzIzemlXcGd3VzZvQ3lnKzdHZ1BmaHZXWXJVcnpJcTVpK3hhNnpWVVBYY0s2aytCekF5Ywpkclo2NXFQMkJpQ0ZyQnlUUWZjNWZVWFF2amZFUTNxQ01KdHh5RVhpSU91TjJCYjZWQUFTSmIxNjlCeGVEVVgyClMzdnBXUkl5b1I3QU8wblFza01FM2k1Ym52clkweDg3aFBBZ0Y1RGtEN1NmTDVkYkp5YUY4QmtDZ1lFQTRCbGkKUTVoNGF2WldzNk1Jdy9MbnVQQXBIL2xoMlR1NXFpNmhnWG11Uk1RL2dzRE9tYzNxTzAyNVN3alB1WUxjMkRsMwo0UWJ3b3JDL0FnS3FRUURDbGZUNEloMmNMRGNYcUxlR1ZteHo1clZsNkJRcU5XeEFac3lCSTZwSjBORmRVR3J6CkdaeUk1RG1QWTRzcVVmR1hWY1M3M25XZHI4Z0psejBDc21ZbFFnY0NnWUVBa2Z4RWZGWVd5T2djWjVrOHgrUkUKRG5SRkJaOUloSmJzVy9YSFJRU2xWUFRrRm53bC9ZTStMZi9LZHhmcjVFL1BDdTZkb2gxSHVLaTZjaDIrWXBuVgpQdklmWVBlekg5eFdMU0dkQmJxMzA3RmpjNDd0UXdVTUl2OEJKU1JPNWNUTzNIc2JoczVCaUtjZ2tmWFltbjB1ClBQUVRSUWRiRmRCYlNYWExCY2ZsTGFFQ2dZRUFyVkUwZkU3cG91QU9RalJ2VFEwS1JqQUh2bURqV2wwa3hRZjMKaE9tVTdENVRXRTdCK3BZVTkvU3V2K2Q2c0dFVGFHOVoxY0hHVGkwZ0xPL2V1Uk5iYXhyZzVaRzgvVDFHb1FmLwpiOHZFLzhOL296UWxTTmdHSHZzL1RWUWdiczNkdTVwYmxZMUpHaW1pU2p5UmFIck9ybGpQYThmUFF1b1U4TkVRCnl1VFJIL1VDZ1lCVCtsZnlxVVRLSURWNnNLSUhGU3ZWdXFpVllrU0hadzRJZk9EVVNGTWRXdVFTY2FaNFZVWW8KQUpFc2IxVWF6NWNVYlFDU3h1ZDU3NlFqaXptUElzMktKbzFtWmYwT2lOWldVT0R2SnltanVXUjIyZFVkWmoyMwpjWHVRYk1RWUkvMWk0R3ZMVHJJeHNiSnlGUjZ1NThMd3c1S0xRYitzM2F4YWhhSk5aSFMybVE9PQotLS0tLUVORCBSU0EgUFJJVkFURSBLRVktLS0tLQo=
---
apiVersion: v1
kind: Service
metadata:
  name: kubeslice-webhook-service
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - port: 443
    targetPort: 9443
  selector:
    control-plane: controller-manager
---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: kubeslice-mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJkakNDQVIyZ0F3SUJBZ0lSQU1RMENRK3Q2RjNSMkhZMnFEVVFlTnd3Q2dZSUtvWkl6ajBFQXdJd0d6RVoKTUJjR0ExVUVBeE1RYlhrdGMyVnNabk5wWjI1bFpDMWpZVEFlRncweU1qQXlNVFl4TVRReU1qRmFGdzB5TWpBMQpNVGN4TVRReU1qRmFNQnN4R1RBWEJnTlZCQU1URUcxNUxYTmxiR1p6YVdkdVpXUXRZMkV3V1RBVEJnY3Foa2pPClBRSUJCZ2dxaGtqT1BRTUJCd05DQUFTWVE4aHE0YWFxbVJUK203dTV3NE96eFpSWjFOM1ZrRGhYOC9XZXBRZ0wKL1ZYMzI3UjBYNEFFdXlMR3JHYmUyQURmSndGa0hEa05EVW1wY3JadFBxZ2pvMEl3UURBT0JnTlZIUThCQWY4RQpCQU1DQXFRd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBZEJnTlZIUTRFRmdRVWhqbWZXZVhiUTlYZzJ2djU3TlE3CjdoNFBGWEV3Q2dZSUtvWkl6ajBFQXdJRFJ3QXdSQUlnQjJWTENZZ3ZKQ3ZTWG83RGVQaGl4VXQ0S3BtOXlUdmoKUXhIYTc5UjF6Z29DSUZyMkVYV3J4V0xxSWJYRDl2YU9qUys1RzZaZ1J4d05UM2FaaFQ5R1FRbFQKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    service:
      name: kubeslice-webhook-service
      namespace: {{ .Release.Namespace }}
      path: /mutate-appsv1-deploy
  failurePolicy: Fail
  name: mdeploy.avesha.io
  rules:
  - apiGroups:
    - apps
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - deployments
  sideEffects: NoneOnDryRun
